### PR TITLE
Make `PodTransmutable` unsafe

### PR DESCRIPTION
**Pull request by Enet4**

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
That effectively just gives users another metaphorical `<h1>` that they should think about this, right without imposing any restrixions?

**Comment by Enet4** [comment]
> That effectively just gives users another metaphorical <h1> that they should think about this, right without imposing any restrixions?

What am I missing? That's the whole point of making a trait `unsafe`: we define the contract, and they implement it at their own risk. What we have without this PR is much worse, considering that it makes an open door to UB in entirely safe code.

**Comment by nabijaczleweli** [comment]
I was asking for clarification, I thought I phrased that understandably, turns out I'ven't.

**Comment by nabijaczleweli** [comment]
Released in [`v0.7.0`](https://github.com/nabijaczleweli/safe-transmute-rs/releases/tag/v0.7.0).

**Pull request merged**
